import { Open_Sans } from 'next/font/google';
import './globals.css';
import Head from 'next/head';

const opensans = Open_Sans({ subsets: ['latin'], variable: '--font-main' });

export const metadata = {
  title: 'Dietrich Schwarz Architekten AG',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Corrected part here */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={opensans.className}>{children}</body>
    </html>
  );
}
