// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  architecture_links: dynamic(() => import("./ArchitectureLinks")),
  employee: dynamic(() => import("./Employee")),
  job_add: dynamic(() => import("./JobAdd")),
  project_info: dynamic(() => import("./ProjectInfo")),
  project_slice: dynamic(() => import("./ProjectSlice")),
};
