// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  project_info: dynamic(() => import("./ProjectInfo")),
  project_slice: dynamic(() => import("./ProjectSlice")),
};
